server:
  port: 5002

spring:
  config:
    import: configserver:http://localhost:8888 #Config server configuration
  application:
     name: advertises-service
  zipkin:
    base-url: http://localhost:9411  
     
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always        

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
    
resilience4j:
  circuitbreaker:
    instances:
      AUTH_TOKEN_VALIDATION:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
